services:

  server:
    user: 1000:1000
    depends_on:
      volume-setup:
        condition: service_completed_successfully

  volume-setup:
    # This service ensures that pi is the owner of the secrets volume, since Docker creates it with
    # root ownership.
    image: docker.io/library/alpine:3.23.0@sha256:51183f2cfa6320055da30872f211093f9ff1d3cf06f39a0bdb212314c5dc7375
    volumes:
      - secrets:/secrets
    command: 'sh -c "chown -R 1000:1000 /secrets; sleep 60"'
