services:

  server:
    user: 1000:1000
    depends_on:
      volume-setup:
        condition: service_completed_successfully

  volume-setup:
    # This service ensures that pi is the owner of the secrets volume, since Docker creates it with
    # root ownership.
    image: docker.io/library/alpine:3.23.2@sha256:865b95f46d98cf867a156fe4a135ad3fe50d2056aa3f25ed31662dff6da4eb62
    volumes:
      - secrets:/secrets
    command: 'sh -c "chown -R 1000:1000 /secrets; sleep 60"'
