services:

  server:
    image: ghcr.io/openuc2/device-admin:0.1.6-alpha.0@sha256:3216e4864198d596dd8d1243ccc2ecc21deee3575d422ebfbff0e956de5da3ae
    environment:
      - HTTP_BASEPATH=/admin/panel/
      - TEMPLATES_PATH=/web/templates
      - ACTIONCABLE_HASH_KEYFILE=/secrets/action-cable/hash.key
    volumes:
      - type: bind
        source: ./templates
        target: /web/templates
        read_only: true
      - type: bind
        source: /run/dbus/system_bus_socket
        target: /var/run/dbus/system_bus_socket
      - type: bind
        source: /run/tailscale/tailscaled.sock
        target: /var/run/tailscale/tailscaled.sock
      - type: bind
        source: /media
        target: /media
      - secrets:/secrets

# TODO(ethanjli): figure out how to enable this! For some reason, I get the following error when I
# uncomment it:
# Error response from daemon: invalid config for network none: invalid endpoint settings:
# network-scoped aliases are only supported for user-defined networks
#
# networks:
#   default:
#     name: none
#     external: true

volumes:
  secrets: null
