services:
  server:
    image: ghcr.io/openuc2/device-admin:0.1.3@sha256:83d257c0fb25bf181b96b00e6b669b048ede9365cc870a7b00387e3931d03884
    environment:
      - HTTP_BASEPATH=/admin/panel/
      - TEMPLATES_PATH=/web/templates
    volumes:
      - type: bind
        source: ./templates
        target: /web/templates
        read_only: true
      - type: bind
        source: /run/dbus/system_bus_socket
        target: /var/run/dbus/system_bus_socket
      - type: bind
        source: /run/tailscale/tailscaled.sock
        target: /var/run/tailscale/tailscaled.sock
networks:
  default:
    name: none
    external: true
