services:
  server:
    image: ghcr.io/openuc2/device-admin:0.1.5-alpha.6@sha256:163d8a1d58a44163db236a2ef860f7d89661826fd18a2d3c95c885067bdd5eeb
    environment:
      - HTTP_BASEPATH=/admin/panel/
      - TEMPLATES_PATH=/web/templates
    volumes:
      - type: bind
        source: ./templates
        target: /web/templates
        read_only: true
      - type: bind
        source: /run/dbus/system_bus_socket
        target: /var/run/dbus/system_bus_socket
      - type: bind
        source: /run/tailscale/tailscaled.sock
        target: /var/run/tailscale/tailscaled.sock
      - type: bind
        source: /media
        target: /media
networks:
  default:
    name: none
    external: true
