#!/bin/bash

export FORKLIFT_STAGE_STORE=/var/lib/forklift/stages

forklift_version=""
factory_reset_bun=""
current_bun=""
next_bun=""
next_failed="" # null, true, or false
if which forklift >/dev/null; then
  forklift_version="$(forklift --version | sed 's~^forklift version ~~')"
fi
if which forklift >/dev/null && which gojq >/dev/null; then
  factory_reset_bun="$(forklift stage locate-bun factory-reset)"
  current_bun="$(forklift stage locate-bun current)"
  next_bun="$(forklift stage locate-bun next)"
  next_failed="$(
    cat "$FORKLIFT_STAGE_STORE/forklift-stage-store.yml" |
      gojq --yaml-input '.staged."next-failed"' -r
  )"
fi

assemble_pallet_identifier() {
  local bundle_path="$1"

  bundle_manifest="$(cat "$bundle_path/forklift-bundle.yml")"
  pallet_path="$(echo "$bundle_manifest" | gojq --yaml-input ".pallet.path" -r)"
  pallet_version="$(echo "$bundle_manifest" | gojq --yaml-input ".pallet.version" -r)"
  is_clean="$(echo "$bundle_manifest" | gojq --yaml-input ".pallet.clean" -r)"
  clean_string=""
  if [ "$is_clean" != "true" ]; then
    clean_string=" (with uncommitted changes)"
  fi

  echo "$pallet_path@$pallet_version$clean_string"
}

echo
if [ "$factory_reset_bun" == "" ]; then
  echo "Couldn't determine the active version of Forklift!"
else
  echo "Forklift: $forklift_version"
fi
if [ "$factory_reset_bun" == "" ]; then
  echo "Couldn't determine the originally-installed version of the OS!"
else
  echo "Originally-installed OS:          $(assemble_pallet_identifier "$factory_reset_bun")"
fi
if [ "$current_bun" == "" ]; then
  echo "Couldn't determine the currently-booted Forklift pallet!"
else
  echo "Currently-booted Forklift pallet: $(assemble_pallet_identifier "$current_bun")"
fi
if [ "$next_bun" == "" ]; then
  echo "Couldn't determine the next Forklift pallet to boot into!"
elif [ "$next_bun" != "$current_bun" ]; then
  echo "Next Forklift pallet to boot as:  $(assemble_pallet_identifier "$current_bun")"
  if [ "$next_failed" == "true" ]; then
    echo "Warning: because the next pallet already failed during a previous boot attempt, future boots will instead fall back to the currently-booted pallet: $(assemble_pallet_identifier "$current_bun")"
    echo 'You can try to boot into the next pallet again by running: forklift stage set-next-result pending'
  fi
fi
