services:
  reverse-proxy-config:
    image: docker.io/library/alpine:3.24.1@sha256:28bd5fe8b56d1bd048e5babf5b10710ebe0bae67db86916198a6eec434943f8b
    command: sh -c 'sleep 60'
networks:
  default:
    name: none
    external: true
