services:
  reverse-proxy-config:
    networks:
      - caddy-ingress
    labels:
      caddy: http://
      # To make Windows 10 or newer detect a captive portal:
      caddy.redir_0: /connecttest.txt /
      # To make Windows 8.1 or below detect a captive portal:
      caddy.redir_1: /ncsi.txt /
      # To make Windows redirect the captive portal to the landing page:
      caddy.redir_2: /redirect /

networks:
  caddy-ingress:
    external: true
