services:
  reverse-proxy-config:
    image: docker.io/library/alpine:3.24.2@sha256:294b683cb724975bec92580e1e685676bd4b50bda910ddb8c51d4cabeaec77e6
    command: sh -c 'sleep 60'
    networks:
      - caddy-ingress
    labels:
      # To make Windows 10 or newer detect a captive portal:
      caddy_1: http://www.msftconnecttest.com
      caddy_1.respond: /connecttest.txt "Microsoft Connect Test"
      # To make Windows 8.1 or below detect a captive portal:
      caddy_2: http://www.msftncsi.com
      caddy_2.respond_1: /ncsi.txt "Microsoft NCSI"

networks:
  default:
    name: none
    external: true
  caddy-ingress:
    external: true
