services:
  internal:
    image: docker.io/lucaslorentz/caddy-docker-proxy:2.13.1@sha256:4c14f2ddb9c259903c464ac0423c936b10757bda7c57f8eb34b93efa903c8b8d
    volumes:
      - type: bind
        source: /run/docker.sock
        target: /var/run/docker.sock
        read_only: true
        bind:
          create_host_path: false
      - internal-data:/data
      - internal-config:/config
    ports:
      - name: internal
        target: 80
        host_ip: 127.0.0.1
        published: 8080
    networks:
      - proxied
    extra_hosts:
      - host.docker.internal:host-gateway
    environment:
      - CADDY_DOCKER_SCAN_STOPPED_CONTAINERS=1
      - CADDY_INGRESS_NETWORKS=caddy-ingress
    labels:
      caddy.auto_https: disable_redirects

  external:
    image: docker.io/library/caddy:2.11.4@sha256:af5fdcd76f2db5e4e974ee92f96ee8c0fc3edb55bd4ba5032547cbf3f65e486d
    network_mode: host
    volumes:
      - type: bind
        source: /run/caddy-ingress/external
        target: /etc/caddy
      - external-data:/data
      - external-config:/config
      - type: bind
        source: /run/tailscale/tailscaled.sock
        target: /var/run/tailscale/tailscaled.sock
    extra_hosts:
      - host.docker.internal:host-gateway
    command: caddy run --config /etc/caddy/Caddyfile --adapter caddyfile --watch
    # TODO: use `caddy reload` or `docker kill --signal="SIGUSR1" {ctr name}` to the signal instead
    # of using `--watch`, which is only meant for use in local dev envs!
    depends_on:
      ensure-external-caddyfile:
        condition: service_completed_successfully

  ensure-external-caddyfile:
    # This service ensures that a valid Caddyfile exists as a fallback even if
    # /run/caddy-ingress/external doesn't exist, so that the container can start successfully
    image: docker.io/library/alpine:3.24.1@sha256:28bd5fe8b56d1bd048e5babf5b10710ebe0bae67db86916198a6eec434943f8b
    volumes:
      - /run/caddy-ingress/external:/etc/caddy
      - ./external.Caddyfile-fallback:/run/caddy/Caddyfile-fallback
    command: 'sh -c "cat /etc/caddy/Caddyfile || cp /run/caddy/Caddyfile-fallback /etc/caddy/Caddyfile"'

volumes:
  internal-data: null
  internal-config: null
  external-data: null
  external-config: null

networks:
  proxied:
    name: caddy-ingress
