package:
  description: >
    Reverse proxy for web services, and configuration of it using Docker container image labels
  maintainers:
    - name: Ethan Li
      email: lietk12@gmail.com
  license: MIT
  sources:
    - https://github.com/lucaslorentz/caddy-docker-proxy

deployment:
  compose-files:
    - deployment.compose.yml
  requires:
    filesets:
      - description: Docker socket
        paths:
          - /run/docker.sock
      - description: Shell script to string-interpolate a templated stdin to stdout
        paths:
          - /usr/libexec/render-templated-config
  provides:
    networks:
      - description: Bridge network for Caddy to connect to upstream services
        name: caddy-ingress
    listeners:
      - description: Web server for HTTP requests from within localhost
        port: 8080
        protocol: tcp
      - description: Web server for HTTP requests from external peers
        port: 80
        protocol: tcp
      - description: Web server for all HTTPS requests
        port: 443
        protocol: tcp
      - description: Web server for all HTTP/3 requests
        port: 443
        protocol: udp
      - description: Caddy admin API endpoint
        port: 2019
        protocol: tcp
    services:
      - description: Web server which reverse-proxies web services on the machine
        tags: [caddy-docker-proxy]
        port: 80
        protocol: http
      - description: >
          Reverse-proxy web server which provides TLS termination to web services on the machine
        tags: [caddy-docker-proxy]
        port: 443
        protocol: https
    file-exports:
      - description: Caddyfile template for ingress proxying external peers
        target: overlays/etc/caddy-ingress/external/Caddyfile.template
      - description:
          systemd service to generate a Caddyfile for ingress proxying external peers from a
          Caddyfile template
        target: overlays/usr/lib/systemd/system/generate-caddy-ingress-external-config.service
      - description: systemd service enablement for generate-caddy-ingress-external-config.service
        target: overlays/etc/systemd/system/forklift-apply.service.wants/generate-caddy-ingress-external-config.service
      - description:
          systemd timer to periodically regenerate the Caddyfile for ingress proxying external peers
        target: overlays/usr/lib/systemd/system/generate-caddy-ingress-external-config.timer
      - description: systemd timer enablement for generate-caddy-ingress-external-config.timer
        target: overlays/etc/systemd/system/multi-user.target.wants/generate-caddy-ingress-external-config.timer

features:
  firewall-allow-direct:
    description:
      Firewall configuration to allow accessing the reverse proxy from directly-connected devices
    requires:
      filesets:
        - description: Drop-in directory for XML fragment files to generate the nm-shared zone definition
          tags:
            - drop-in-assembly
          paths:
            - /etc/firewalld/zones.d/nm-shared
    provides:
      file-exports:
        - description: Drop-in XML fragment for firewalld's HTTP service
          target: overlays/etc/firewalld/zones.d/nm-shared/60-service-http.xml
        - description: Drop-in XML fragment for firewalld's HTTPS
          target: overlays/etc/firewalld/zones.d/nm-shared/60-service-https.xml
  firewall-allow-public:
    description:
      Firewall configuration to allow public access to the reverse proxy
    requires:
      filesets:
        - description: Drop-in directory for XML fragment files to generate the public zone definition
          tags:
            - drop-in-assembly
          paths:
            - /etc/firewalld/zones.d/public
    provides:
      services:
        - description: Port in the public firewall zone
          port: 80
          protocol: http-public
      file-exports:
        - description: Drop-in XML fragment for firewalld's HTTP service
          target: overlays/etc/firewalld/zones.d/public/60-service-http.xml
        - description: Drop-in XML fragment for firewalld's HTTPS service
          target: overlays/etc/firewalld/zones.d/public/60-service-https.xml
