services:
  https:
    image: docker.io/library/caddy:2.11.1@sha256:9068f76202c0a03545036d32bf2d424d3b46c1174f254070f605002a2dbc9657
    networks:
      - host
    volumes:
      - type: bind
        source: /run/caddy-ingress/https
        target: /etc/caddy
      - https-data:/data
      - https-config:/config
      - type: bind
        source: /run/tailscale/tailscaled.sock
        target: /var/run/tailscale/tailscaled.sock
    extra_hosts:
      - host.docker.internal:host-gateway
    command: caddy run --config /etc/caddy/Caddyfile --adapter caddyfile --watch
    depends_on:
      ensure-caddyfile:
        condition: service_completed_successfully

  ensure-caddyfile:
    # This service ensures that a valid Caddyfile exists as a fallback even if
    # /run/caddy-ingress/https doesn't exist, so that the container can start successfully
    image: docker.io/library/alpine:3.23.3@sha256:25109184c71bdad752c8312a8623239686a9a2071e8825f20acb8f2198c3f659
    volumes:
      - /run/caddy-ingress/https:/etc/caddy
      - ./https.Caddyfile-fallback:/run/caddy/Caddyfile-fallback
    command: 'sh -c "cat /etc/caddy/Caddyfile || cp /run/caddy/Caddyfile-fallback /etc/caddy/Caddyfile"'

volumes:
  https-data: null
  https-config: null
