services:
  server:
    ports:
      - 80:80
      - 443:443/tcp
      - 443:443/udp
    networks:
      - proxied
    environment:
      - CADDY_INGRESS_NETWORKS=caddy-ingress
    labels:
      caddy.auto_https: disable_redirects

networks:
  default:
    name: none
    external: true
  proxied:
    name: caddy-ingress
