services:

  server:
    image: ghcr.io/openuc2/device-portal:0.2.0-alpha.0@sha256:c8e7a5cf93c80ee3a91b424d51a23e0b5a5b4d1a071d463497908c001c2d5040
    environment:
      - TEMPLATES_PATH=/web/templates
    volumes:
      - type: bind
        source: ./templates
        target: /web/templates
        read_only: true

  server-untrusted:
    image: ghcr.io/openuc2/device-portal:0.2.0-alpha.0@sha256:c8e7a5cf93c80ee3a91b424d51a23e0b5a5b4d1a071d463497908c001c2d5040
    environment:
      - TEMPLATES_PATH=/web/templates
    volumes:
      - type: bind
        source: ./templates-untrusted
        target: /web/templates
        read_only: true
