services:
  server:
    image: ghcr.io/openuc2/machine-portal:0.3.0-alpha.0@sha256:7ec1e2a7f3f07ae6d2bc25ec22a403afe0d5649179d599bdc1632a52926f551a
    environment:
      - TEMPLATES_PATH=/web/templates
    volumes:
      - type: bind
        source: ./templates
        target: /web/templates
        read_only: true
