package:
  description: Landing page for easy access to deployed browser applications
  maintainers:
    - name: Ethan Li
      email: lietk12@gmail.com
  license: Apache-2.0
  sources:
    # Forklift-deployed software Apache-2.0):
    - https://github.com/openUC2/machine-portal
    # Templates (Apache-2.0):
    - https://github.com/openUC2/os-rpi

deployment:
  compose-files:
    - deployment.compose.yml

features:
  frontend:
    description: Provides access to a browser landing page
    compose-files:
      - frontend.compose.yml
    requires:
      networks:
        - description: Overlay network for Caddy to connect to upstream services
          name: caddy-ingress
      services:
        - tags: [caddy-docker-proxy]
          port: 80
          protocol: http
    provides:
      services:
        - description: Landing page for the machine's network services
          port: 80
          protocol: http
          paths:
            - /
            - /favicon.ico
            - /app/*
            - /static/*
            - /fonts/*
  deploy-rpi:
    description: Integrates with Imswitch OS
    compose-files:
      - deploy-rpi.compose.yml
  dev-mock:
    description: Provides a fake machine name, to enable development & testing outside openUC2 OS
    compose-files:
      - dev-mock.compose.yml
  untrusted:
    description: Provides a browser landing page for untrusted users
    compose-files:
      - untrusted.compose.yml
  frontend-untrusted:
    description: Provides untrusted access to the untrusted browser landing page
    compose-files:
      - frontend-untrusted.compose.yml
    requires:
      networks:
        - description: Overlay network for Caddy to connect to upstream services
          name: caddy-ingress-untrusted
      services:
        - tags: [caddy-docker-proxy]
          port: 8000
          protocol: http
    provides:
      services:
        - description: Landing page for the machine's network services
          port: 8000
          protocol: http
          paths:
            - /
            - /favicon.ico
            - /app/*
            - /static/*
            - /fonts/*
  deploy-rpi-untrusted:
    description: Integrates with Imswitch OS for untrusted access
    compose-files:
      - deploy-rpi-untrusted.compose.yml
  dev-mock-untrusted:
    description: Provides a fake machine name for untrusted access, to enable development & testing outside openUC2 OS
    compose-files:
      - dev-mock-untrusted.compose.yml
