services:
  server:
    image: ghcr.io/youseetoo/firmware-image-server:sha-a969088
    volumes:
      - server-data:/data
      - server-config:/config
volumes:
  server-data: null
  server-config: null
