services:
  server:
    image: ghcr.io/gtsteffaniak/filebrowser:2.1.0-beta-slim@sha256:47379d59d64ce2b124311f81c920d305fb8b8610b086a7478f95c16dd0cd2744
    volumes:
      - type: bind
        source: /
        target: /root
        bind:
          create_host_path: false
      - type: bind
        source: deployment.filebrowser.yml
        target: /configs/deployment.filebrowser.yml
        bind:
          create_host_path: false
      - server-data:/data
    environment:
      - FILEBROWSER_CONFIG=/configs/deployment.filebrowser.yml

  volume-setup:
    # This service ensures that root isn't the owner of /data, since Docker auto-creates those paths
    # with root ownership.
    image: docker.io/library/alpine:3.24.2@sha256:294b683cb724975bec92580e1e685676bd4b50bda910ddb8c51d4cabeaec77e6
    network_mode: none
    volumes:
      - server-data:/data
    command: 'chown -R 1000:1000 /data"'

volumes:
  server-data: {}
