services:
  server:
    image: docker.io/filebrowser/filebrowser:v2.63.16@sha256:a6653eb79ecf8312f4f6bf0d0adf65d81016f17a92d64d5b2562340984e39405
    volumes:
      - type: bind
        source: /
        target: /root
        bind:
          create_host_path: false
      - type: bind
        source: /
        target: /srv # this prevents filebrowser from making an unnamed volume
        bind:
          create_host_path: false
      - server-data:/database
    environment:
      - FB_DATABASE=/database/filebrowser.db
      - FB_ROOT=/root

volumes:
  server-data: {}
