services:
  server:
    image: ghcr.io/gsteffaniak/filebrowser:2.0.8-beta-slim@sha256:91b5d223243b838c0d8f26c508e0194994ca951f0d96ef271d78b3ef1f71abe1
    volumes:
      - type: bind
        source: /
        target: /root
        bind:
          create_host_path: false
      - type: bind
        source: deployment.filebrowser.yml
        target: /configs/deployment.filebrowser.yml
        bind:
          create_host_path: false
      - server-data:/data
    environment:
      - FILEBROWSER_CONFIG=/configs/deployment.filebrowser.yml
      - FB_DATABASE=/database/filebrowser.db
      - FB_ROOT=/root

volumes:
  server-data: {}
