services:
  server:
    volumes:
      - type: bind
        source: frontend.filebrowser.yml
        target: /configs/frontend.filebrowser.yml
        bind:
          create_host_path: false
    networks:
      - caddy-ingress-untrusted
    environment:
      - FILEBROWSER_CONFIG=/configs/frontend.filebrowser.yml
    labels:
      caddy: http://
      caddy.redir: /admin/fs /admin/fs/
      # Public endpoints (no authentication)
      caddy.handle_path: /admin/fs/public/*
      caddy.handle_path.reverse_proxy: "{{upstreams 80}}"
      caddy.handle_path.reverse_proxy.header_up_0: "Host {host}"
      caddy.handle_path.reverse_proxy.header_up_1: "X-Forwarded-For {remote_host}"
      caddy.handle_path.reverse_proxy.header_up_2: "X-Forwarded-Proto {scheme}"
      # Private endpoints
      caddy.handle: /admin/fs/*
      caddy.handle.reverse_proxy: "{{upstreams 80}}"
      caddy.handle.reverse_proxy.header_up_0: "Host {host}"
      caddy.handle.reverse_proxy.header_up_1: "X-Forwarded-For {remote_host}"
      caddy.handle.reverse_proxy.header_up_2: "X-Forwarded-Proto {scheme}"
      # Support file uploads:
      caddy.handle.reverse_proxy.header_up_3: "Connection {>Connection}"
      caddy.handle.reverse_proxy.header_up_4: "Transfer-Encoding {>Transfer-Encoding}"

networks:
  default:
    name: none
    external: true
  caddy-ingress-untrusted:
    external: true
