services:
  server:
    image: ghcr.io/openuc2/imswitch:sha-31d3aa1
    volumes:
      - /etc/machine-id:/etc/machine-id:ro
      - /home/pi/ImSwitchConfig:/home/pi/ImSwitchConfig
      - /home/pi/Datasets:/home/pi/Datasets
      - /media:/media
      - /run/udev:/run/udev:ro
      - /dev:/dev
    device_cgroup_rules:
      - 'a 188:* rwm' # USB serial devices (such as the openUC2 HAT+), e.g. /dev/ttyUSB0
      - 'a 166:* rwm' # USB serial devices (such as SeeedStudio XIAO microcontrollers), e.g. /dev/ttyACM0
      # - 'a 204:* rwm' # Serial devices, e.g. /dev/ttyAMA0
      - 'a 81:* rwm' # libcamera-based cameras, e.g. /dev/video0
      - 'a 511:* rwm' # libcamera-based cameras, e.g. /dev/media0
      # - 'a 89:* rwm' # I2C devices, e.g. /dev/i2c-1
      # - 'a 254:* rwm' # GPIO devices, e.g. /dev/gpiochip0
      # - 'a 235:* rwm' # GPIO devices, e.g. /dev/gpiomem0
      # - 'a 239:* rwm' # GPIO devices, e.g. /dev/gpiomem1
      # - 'a 238:* rwm' # GPIO devices, e.g. /dev/gpiomem2
      # - 'a 237:* rwm' # GPIO devices, e.g. /dev/gpiomem3
      # - 'a 236:* rwm' # GPIO devices, e.g. /dev/gpiomem4
      # - 'a *:* rwm' # allow all devices; only use this for debugging! Don't use this in production, because it's a massive security backdoor!
    group_add:
      - tty
      - dialout
      - video
      - plugdev
      # - i2c
      # - gpio
    environment:
      - HEADLESS=1
      - HTTP_PORT=8001
      - CONFIG_PATH=/home/pi/ImSwitchConfig
      - UPDATE_GIT=0
      - UPDATE_CONFIG=0
      - DATA_PATH=/home/pi/Datasets
      - SCAN_EXT_DATA_PATH=1
      - EXT_DATA_PATH=/media
      - SSL=0
    extra_hosts:
      - host.docker.internal:host-gateway
    depends_on:
      volume-setup:
        condition: service_completed_successfully
    restart: always

  volume-setup:
    # This service ensures that root isn't the owner of /home/pi/Datasets and
    # /home/pi/ImSwitchConfig, since Docker auto-creates those paths if they didn't exist before
    # for the bind mounts, and Docker creates such directories with root ownership.
    image: docker.io/library/alpine:3.24.1@sha256:28bd5fe8b56d1bd048e5babf5b10710ebe0bae67db86916198a6eec434943f8b
    volumes:
      - /home/pi/Datasets:/home/pi/Datasets
      - /home/pi/ImSwitchConfig:/home/pi/ImSwitchConfig
    command: 'sh -c "chown -R 1000:1000 /home/pi/Datasets /home/pi/ImSwitchConfig"'
