services:
  server:
    image: ghcr.io/openuc2/imswitch:pr-291@sha256:36c5e2041e1052650395d74445dda984edb995d2fbdbab63b149bc90a73b3502
    volumes:
      - /etc/machine-id:/etc/machine-id:ro
      - /home/pi/ImSwitchConfig:/home/pi/ImSwitchConfig
      - /home/pi/Datasets:/home/pi/Datasets
      - /media:/media
      - /run/udev:/run/udev:ro
      - /dev:/dev
    device_cgroup_rules:
      - 'a *:* rwm' # allow all devices; only use this for debugging! Don't use this in production, because it's a massive security backdoor!
      - 'a 188:* rwm' # USB serial devices, e.g. /dev/ttyUSB0
      - 'a 204:* rwm' # more USB serial devices (including Daheng cameras), e.g. /dev/ttyAMA0
      - 'a 81:* rwm' # libcamera-based cameras, e.g. /dev/video0
      - 'a 511:* rwm' # libcamera-based cameras, e.g. /dev/media0
      - 'a 153:* rwm' # SPI devices, e.g. /dev/spidev0.1
      # - 'a 89:* rwm' # I2C devices, e.g. /dev/i2c-1
      # - 'a 254:* rwm' # GPIO devices, e.g. /dev/gpiochip0
      # - 'a 235:* rwm' # GPIO devices, e.g. /dev/gpiomem0
      # - 'a 239:* rwm' # GPIO devices, e.g. /dev/gpiomem1
      # - 'a 238:* rwm' # GPIO devices, e.g. /dev/gpiomem2
      # - 'a 237:* rwm' # GPIO devices, e.g. /dev/gpiomem3
      # - 'a 236:* rwm' # GPIO devices, e.g. /dev/gpiomem4
    group_add:
      - tty
      - dialout
      - video
      - plugdev
      - spi
      # - i2c
      # - gpio
    environment:
      - HEADLESS=1
      - HTTP_PORT=8001
      - CONFIG_PATH=/home/pi/ImSwitchConfig
      - UPDATE_GIT=0
      - UPDATE_CONFIG=0
      - DATA_PATH=/home/pi/Datasets
      - SCAN_EXT_DATA_PATH=1
      - EXT_DATA_PATH=/media
      - SSL=0
    extra_hosts:
      - host.docker.internal:host-gateway
    depends_on:
      volume-setup:
        condition: service_completed_successfully
    restart: always

  volume-setup:
    # This service ensures that root isn't the owner of /home/pi/Datasets and
    # /home/pi/ImSwitchConfig, since Docker auto-creates those paths if they didn't exist before
    # for the bind mounts, and Docker creates such directories with root ownership.
    image: docker.io/library/alpine:3.23.4@sha256:5b10f432ef3da1b8d4c7eb6c487f2f5a8f096bc91145e68878dd4a5019afde11
    volumes:
      - /home/pi/Datasets:/home/pi/Datasets
      - /home/pi/ImSwitchConfig:/home/pi/ImSwitchConfig
    command: 'sh -c "chown -R 1000:1000 /home/pi/Datasets /home/pi/ImSwitchConfig"'
