services:
  server:
    image: ghcr.io/openuc2/imswitch:sha-c23b0ae@sha256:08f88200445f4651ec32a4c46b2d8fe6c58bc8b7145722d36da707aa8ce29a50
    privileged: true
    volumes:
      - /etc/machine-id:/etc/machine-id:ro
      - /home/pi/ImSwitchConfig:/home/pi/ImSwitchConfig
      - /home/pi/Datasets:/home/pi/Datasets
      - /media:/media
      - /run/udev:/run/udev:ro
      - /dev/dma_heap:/dev/dma_heap
    environment:
      - HEADLESS=1
      - HTTP_PORT=8001
      - CONFIG_PATH=/home/pi/ImSwitchConfig
      - UPDATE_GIT=0
      - UPDATE_CONFIG=0
      - DATA_PATH=/home/pi/Datasets
      - SCAN_EXT_DATA_PATH=1
      - EXT_DATA_PATH=/media
      - SSL=0
    depends_on:
      volume-setup:
        condition: service_completed_successfully
    restart: always

  volume-setup:
    # This service ensures that root isn't the owner of /home/pi/Datasets and
    # /home/pi/ImSwitchConfig, since Docker auto-creates those paths if they didn't exist before
    # for the bind mounts, and Docker creates such directories with root ownership.
    image: docker.io/library/alpine:3.23.2@sha256:865b95f46d98cf867a156fe4a135ad3fe50d2056aa3f25ed31662dff6da4eb62
    volumes:
      - /home/pi/Datasets:/home/pi/Datasets
      - /home/pi/ImSwitchConfig:/home/pi/ImSwitchConfig
    command: 'sh -c "chown -R 1000:1000 /home/pi/Datasets /home/pi/ImSwitchConfig"'
