services:
  server:
    networks:
      - caddy-ingress
    labels:
      caddy: http://
      caddy.redir_0: /imswitch /imswitch/
      caddy.handle_0: /imswitch/*
      caddy.handle_0.reverse_proxy: "{{upstreams 8001}}"
      caddy.redir_1: /jupyter /jupyter/
      caddy.handle_1: /jupyter/*
      caddy.handle_1.reverse_proxy: "{{upstreams 8888}}"

networks:
  caddy-ingress:
    external: true
