services:

  server:
    image: ghcr.io/openuc2/machine-admin:0.1.6-alpha.8@sha256:dd8fa8818305f6abe398ac003fb4608f95766515ef87914b0e73029d6fb50c15
    command: server
    user: 1000:1000
    environment:
      - HTTP_BASEPATH=/admin/panel/
      - TEMPLATES_PATH=/web/templates
      - ACTIONCABLE_HASH_KEYFILE=/secrets/action-cable/hash.key
      - SIDECAR_ADDRESS=tcp:sidecar:2312
    networks:
      - sidecar
    volumes:
      # - type: bind
      #   source: ./templates
      #   target: /web/templates
      #   read_only: true
      - type: bind
        source: /run/versioning
        target: /run/versioning
        read_only: true
      - type: bind
        source: /run/machine-name
        target: /run/machine-name
        read_only: true
      - type: bind
        source: /etc/hostname
        target: /etc/hostname
        read_only: true
      - type: bind
        source: /run/dbus/system_bus_socket
        target: /var/run/dbus/system_bus_socket
      - type: bind
        source: /run/tailscale/tailscaled.sock
        target: /var/run/tailscale/tailscaled.sock
      - type: bind
        source: /media
        target: /media
      - secrets:/secrets
    restart: always
    depends_on:
      volume-setup:
        condition: service_completed_successfully

  sidecar:
    image: ghcr.io/openuc2/machine-admin:0.1.6-alpha.8@sha256:dd8fa8818305f6abe398ac003fb4608f95766515ef87914b0e73029d6fb50c15
    command: sidecar
    environment:
      - SIDECAR_ADDRESS=tcp:0.0.0.0:2312
    networks:
      - sidecar
    volumes:
      - type: bind
        source: /etc/NetworkManager/system-connections.d
        target: /etc/NetworkManager/system-connections.d
      - type: bind
        source: /run/dbus/system_bus_socket
        target: /var/run/dbus/system_bus_socket
    restart: always

  volume-setup:
    # This service ensures that pi is the owner of the secrets volume, since Docker creates it with
    # root ownership.
    image: docker.io/library/alpine:3.24.0@sha256:a2d49ea686c2adfe3c992e47dc3b5e7fa6e6b5055609400dc2acaeb241c829f4
    networks:
      - sidecar
    volumes:
      - secrets:/secrets
    command: 'sh -c "chown -R 1000:1000 /secrets"'

networks:
  default:
    name: none
    external: true
  sidecar:
volumes:
  secrets: null
