services:
  server:
    image: docker.io/filebrowser/filebrowser:v2.63.21@sha256:b1d9980d79d6d0ad334e327eea3501324a07fe2bce94a4cd84187bccbcfbe3f8
    volumes:
      - type: bind
        source: /
        target: /root
        bind:
          create_host_path: false
      - type: bind
        source: /
        target: /srv # this prevents filebrowser from making an unnamed volume
        bind:
          create_host_path: false
      - server-data:/database
    environment:
      - FB_DATABASE=/database/filebrowser.db
      - FB_ROOT=/root
    user: root

volumes:
  server-data: {}
