services:
  server:
    networks:
      - caddy-ingress
    environment:
      - FB_PORT=80 # for some reason filebrowser doesn't work if this is port 8080
      - FB_BASE_URL=/admin/fs-su
      - FB_NOAUTH=true
    labels:
      caddy: http://, https://, *.ts.net
      caddy.redir: /admin/fs-su /admin/fs-su/
      caddy.handle: /admin/fs-su/*
      caddy.handle.reverse_proxy: "{{upstreams 80}}"

networks:
  default:
    name: none
    external: true
  caddy-ingress:
    external: true
