services:
  server:
    volumes:
      - type: bind
        source: frontend.filebrowser.yml
        target: /configs/frontend.filebrowser.yml
        bind:
          create_host_path: false
    networks:
      - caddy-ingress
    environment:
      - FILEBROWSER_CONFIG=/configs/frontend.filebrowser.yml
    labels:
      caddy: http://
      caddy.redir: /admin/fs-su /admin/fs-su/

      # Public endpoints (no authentication)
      caddy.handle_0: /admin/fs-su/public/*
      caddy.handle_0.reverse_proxy: "{{upstreams 80}}"
      caddy.handle_0.reverse_proxy.header_up_0: "Host {host}"
      caddy.handle_0.reverse_proxy.header_up_1: "X-Forwarded-For {remote_host}"
      caddy.handle_0.reverse_proxy.header_up_2: "X-Forwarded-Proto {scheme}"

      # Private endpoints
      caddy.handle_1: /admin/fs-su/*
      caddy.handle_1.reverse_proxy: "{{upstreams 80}}"
      caddy.handle_1.reverse_proxy.header_up_0: "Host {host}"
      caddy.handle_1.reverse_proxy.header_up_1: "X-Forwarded-For {remote_host}"
      caddy.handle_1.reverse_proxy.header_up_2: "X-Forwarded-Proto {scheme}"
      # Support file uploads:
      caddy.handle_1.reverse_proxy.header_up_3: "Connection {>Connection}"
      caddy.handle_1.reverse_proxy.header_up_4: "Transfer-Encoding {>Transfer-Encoding}"

networks:
  default:
    name: none
    external: true
  caddy-ingress:
    external: true
