services:
  lepmonos:
    image: ghcr.io/desboe/lepmonos:arm64-latest@sha256:6fd27c3cfce0619c94767cde0bec9ce9ae1909ba3132c363c8df819dcfdffa26
    privileged: true
    ports:
      - "3000:3000"
      - "8002:8002"
      - "8001:8001"
      - "8888:8888"
      - "2222:22"
    volumes:
      - /home/pi/:/config
      - /home/pi/:/dataset
      - /tmp:/tmp
      - /home/pi/LepmonOS:/home/pi/LepmonOS
    restart: always
