#!/bin/bash -eu
shopt -s nullglob

user="$1"

# Extract all init-root archives in lexicographical order:
rm -rf "/run/init-root/as-$user/"
mkdir -p "/run/init-root/as-$user/"
cp -rT "/boot/firmware/init-root/as-$user/" "/run/init-root/as-$user/"
chown -R "$user:$user" "/run/init-root/as-$user/"

# FIXME: don't overwrite any directories which already exist!
cp -rp /run/init-root/as-%i/* /

find /boot/firmware/init-root/as-%i/ -type f -exec rm {} +
