#!/bin/bash -eu
shopt -s nullglob

# Extract all init-root archives in lexicographical order:
for archive in /boot/firmware/init-root-*.tar.gz; do
  echo "$archive:"
  tar -tzf "$archive"
  echo
  tar \
    -C / \
    -xzfp "$archive"
  rm "$archive"
  echo
done
