#!/bin/bash -eu

user="$1"

# Extract all init-root archives in lexicographical order:
rm -rf "/run/init-root/as-$user/"
mkdir -p "/run/init-root/as-$user/"
cp -rT "/boot/firmware/init-root/as-$user/" "/run/init-root/as-$user/"
chown -R "$user:$user" "/run/init-root/as-$user/"

find . -type d -empty -delete # don't copy empty directories into the root fs
cp -r /run/init-root/as-"$user"/* /

find "/boot/firmware/init-root/as-$user/" -type f -exec rm {} +
