services:
  server:
    image: docker.io/amir20/dozzle:v10.9.0@sha256:7f01a2504f89788b60ad0efddd94472fd66f9a225c708356cdb815d9d8abd184
    volumes:
      - type: bind
        source: /run/docker.sock
        target: /var/run/docker.sock
        bind:
          create_host_path: false
    environment:
      - DOZZLE_ENABLE_ACTIONS=true
