services:
  server:
    image: docker.io/amir20/dozzle:v10.3.0@sha256:034bb79c668dbd861e8d1ea131ad9c7abfe136e423edf80efaf502f8aae9c127
    volumes:
      - type: bind
        source: /run/docker.sock
        target: /var/run/docker.sock
        bind:
          create_host_path: false
    environment:
      - DOZZLE_ENABLE_ACTIONS=true
