services:
  server:
    image: ghcr.io/openuc2/serial-monitor:sha-bda6220@sha256:caa146c276124a25cb972f82b8e6cb174e68da2cca24d816c81d64a491c3c661
    privileged: true
    ports:
      - 3010:3010
    volumes:
      - type: bind
        source: /dev
        target: /dev
        bind:
          create_host_path: false
      - type: bind
        source: /sys
        target: /sys
        read_only: true
        bind:
          create_host_path: false
      - type: bind
        source: /run/udev
        target: /run/udev
        read_only: true
        bind:
          create_host_path: false
