services:
  server:
    image: ghcr.io/openuc2/serial-monitor:sha-018a8cc@sha256:c12ae4e40cc1809fc8b39847304974b9ad2450030eb2aa3bfd78cea78c73d633
    privileged: true
    ports:
      - 3010:3010
    volumes:
      - type: bind
        source: /dev
        target: /dev
        bind:
          create_host_path: false
      - type: bind
        source: /sys
        target: /sys
        read_only: true
        bind:
          create_host_path: false
      - type: bind
        source: /run/udev
        target: /run/udev
        read_only: true
        bind:
          create_host_path: false
