services:
  server:
    networks:
      - caddy-ingress
    labels:
      caddy: http://
      caddy.redir: /dev/serial-monitor /dev/serial-monitor/
      caddy.handle: /dev/serial-monitor/*
      caddy.handle.reverse_proxy: "{{upstreams 3010}}"

networks:
  default:
    name: none
    external: true
  caddy-ingress:
    external: true
