services:
  server:
    image: ghcr.io/openuc2/docs:sha-0017b7e@sha256:e6897e16792a4f148ebe30e5b180f2de7094b3131eb0363f6b1c22329ec62fb2
    volumes:
      - server-data:/data
      - server-config:/config
volumes:
  server-data: null
  server-config: null
