services:
  server:
    image: ghcr.io/openuc2/project-docs:sha-77e654e@sha256:d85569d121f0e0acc0103c30c7d74ae146ffe346be00d6bfe3921c41969d68e7
    volumes:
      - server-data:/data
      - server-config:/config
volumes:
  server-data: null
  server-config: null
