services:
  server:
    image: ghcr.io/openuc2/docs:sha-8d6963e@sha256:bb91848f88358c2f94554e03a3b7d2e3efbea5e78b740bb3c232865e218adbb8
    volumes:
      - server-data:/data
      - server-config:/config
volumes:
  server-data: null
  server-config: null
