services:
  server:
    networks:
      - caddy-ingress-public
    labels:
      caddy: http://
      caddy.redir: /docs /docs/
      caddy.handle: /docs/*
      caddy.handle.reverse_proxy: "{{upstreams 80}}"

networks:
  default:
    name: none
    external: true
  caddy-ingress-public:
    external: true
