services:
  server:
    networks:
      - caddy-ingress
    labels:
      caddy: http://, https://, *.ts.net
      caddy.redir: /openUC2 /openUC2/
      caddy.handle: /openUC2/*
      caddy.handle.reverse_proxy: "{{upstreams 80}}"

networks:
  default:
    name: none
    external: true
  caddy-ingress:
    external: true
