#!/bin/bash -eu

tailscale_dns_name=""
if which tailscale >/dev/null && which gojq >/dev/null && systemctl is-active --quiet tailscaled.service; then
  tailscale_status="$(tailscale status --peers=false --json)"
  tailscale_dns_name="$(echo "$tailscale_status" | gojq ".Self.DNSName" -r | sed 's~\.$~~')"
  tailscale_cert_domain="$(echo "$tailscale_status" | gojq ".CertDomains[0]" -r)"
fi

if [ "$tailscale_dns_name" != "" ]; then
  echo
  echo "Tailscale DNS name: $tailscale_dns_name"
  echo
fi
