#!/bin/bash -eu

tailscale_dns_name=""

# Load values of interpolated variables:
if which tailscale >/dev/null && which gojq >/dev/null && systemctl is-active --quiet tailscaled.service; then
  tailscale_status="$(tailscale status --peers=false --json)"
  tailscale_dns_name="$(echo "$tailscale_status" | gojq ".Self.DNSName" -r | sed 's~\.$~~')"
fi

# Load and string-interpolate templates:
if [ "$tailscale_dns_name" != "" ]; then
  echo "Tailscale DNS name: $tailscale_dns_name"
fi
