---
name: build-os-trixie
on:
  workflow_dispatch:
    inputs:
      git-ref:
        description: 'Git ref (optional)'
        required: false

jobs:
  build:
    name: build
    permissions:
      contents: read
      packages: write
      id-token: write
    uses: ./.github/workflows/build-os.yml
    secrets: inherit
    with:
      name: os-rpi
      build_variant: dx
      base_release_name: trixie
      base_image_variant: lite
      base_release_date: 2025-12-04
      base_file_release_date: 2025-12-04
      arch: arm64
